export { ILoginParams } from "./ILoginParams";
export { IListParams } from "./IListParams";
export { IUserParams } from "./IUserParams";
export { IResidenceParams } from "./IResidenceParams";
export { IChargerParams } from "./IChargerParams";
export { ICompanyInfoParams } from "./ICompanyInfoParams";
export { IWorkerParams } from "./IWorkerParams";
export { IBindOperatorParams } from "./IBindOperatorParams";
export { IGetBoundResidencesParams } from "./IGetBoundResidencesParams";
